name: release

on:
  push:
    branches: [ "main" ]
    paths: [ "v.mod" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "v.mod" ]

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ENV.SET
        run: |
          echo "version=$(grep 'version:' v.mod | grep -oP '\d+\.\d+\.\d+')" >> $GITHUB_ENV

      - name: REPO.RELEASE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${version}" \
            --generate-notes
