name: tests

on:
  pull_request_target:
    branches: [ "main" ]
    paths:
      - '**.v'
      - '**.vsh'
      - '**.vtmpl'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: V:INSTALL
        run: |
          wget -qO /tmp/v.zip https://github.com/vlang/v/releases/latest/download/v_linux.zip
          unzip -q /tmp/v.zip -d /tmp
          echo /tmp/v >> "$GITHUB_PATH"

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: APP:BUILD
        run: |
          ./bin/gen.vsh

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: APP:TEST
        run: |
          v test .
