name: tests

on:
  pull_request_target:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: V:INSTALL
        run: |
          wget -qO /tmp/v.zip https://github.com/vlang/v/releases/latest/download/v_linux.zip
          unzip -q /tmp/v.zip -d /tmp
          echo /tmp/v >> "$GITHUB_PATH"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: APP:TEST
        run: |
          v test .
